Nama : Andhika Fhariel Fadhlurrohman

NIM : 2509116083

Kelas C 2025

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
file = '/content/consumer_electronics_sales_data.csv'

df = pd.read_csv(file)
df

,ProductID,ProductCategory,ProductBrand,ProductPrice,CustomerAge,CustomerGender,PurchaseFrequency,CustomerSatisfaction,PurchaseIntent
0,5874,Smartphones,Other Brands,312.949668,18,0,2,1,0
1,5875,Smart Watches,Samsung,980.389404,35,1,7,2,1
2,5876,Tablets,Samsung,2606.718293,63,0,1,5,1
3,5877,Smartphones,Samsung,870.395450,63,1,10,3,1
4,5878,Tablets,Sony,1798.955875,57,0,17,3,0
...,...,...,...,...,...,...,...,...,...
8995,14869,Smart Watches,Samsung,1041.149163,36,1,16,4,0
8996,14870,Smartphones,Samsung,1485.694311,57,0,5,1,1
8997,14871,Headphones,Samsung,2887.369597,28,0,18,4,0
8998,14872,Tablets,HP,1490.453964,38,0,4,2,1
8999,14873,Smartphones,Sony,2315.583087,62,0,15,2,1

# **Business Understanding**

Pasar elektronik konsumen sangat kompetitif dengan siklus hidup produk yang pendek. Perusahaan ritel sering kali memiliki data transaksi yang besar namun kesulitan untuk memahami siapa pelanggan mereka sebenarnya dan produk apa yang paling menguntungkan. Tanpa pemahaman ini, strategi pemasaran dan stok barang sering kali tidak tepat sasaran.

## **Business Objective**

 Tujuan utama dari inisiatif bisnis ini adalah untuk memacu pertumbuhan pendapatan melalui strategi berbasis data yang komprehensif. Dengan mengidentifikasi faktor penentu total belanja pelanggan, perusahaan dapat secara efektif meningkatkan volume penjualan sekaligus mengoptimalkan personalisasi pemasaran melalui pemetaan preferensi produk—seperti Laptop, Smartphone, dan TV berdasarkan demografi umur serta gender. Selain itu, analisis ini bertujuan untuk mencapai efisiensi operasional melalui optimalisasi inventaris yang presisi, yang didasarkan pada pemahaman mendalam mengenai pola waktu puncak pembelian dan tingkat perputaran produk yang paling diminati di pasar.

## **Asses Situasion**

Analisis ini memanfaatkan dataset komprehensif yang mencakup profil pelanggan (ID, umur, gender), detail transaksi (kategori produk, kuantitas, harga), serta data penilaian produk untuk mengukur kepuasan konsumen. Meskipun proses identifikasi tren dibatasi oleh anonimitas data yang meniadakan variabel lokasi geografis, seluruh pengolahan dan pemodelan dilakukan secara efisien menggunakan ekosistem Python khususnya pustaka Pandas, Matplotlib, dan Scikit Learn di dalam lingkungan kerja Google Colab yang kolaboratif.

## **Analytic Goals**

Proses analisis data ini dilakukan secara bertahap, dimulai dari Analisis Deskriptif untuk memetakan performa produk unggulan, profil demografi target pasar, serta tren musiman guna menangkap dinamika penjualan historis. Langkah ini diperdalam melalui Analisis Diagnostik yang mengevaluasi elastisitas harga terhadap kuantitas penjualan serta korelasi kategori produk dengan tingkat kepuasan pelanggan untuk mengidentifikasi akar permasalahan performa pasar. Untuk memitigasi risiko masa depan, Analisis Prediktif diterapkan menggunakan model regresi dan klasifikasi untuk memproyeksikan nilai transaksi serta perilaku pembelian pelanggan baru. Seluruh temuan tersebut kemudian dikonversi menjadi strategi konkret dalam Analisis Preskriptif, yang mencakup rekomendasi bundling produk yang sinergis serta optimasi kebijakan diskon yang presisi untuk menstimulasi kategori produk dengan perputaran rendah.

## **Project Plan**

# **Data Understanding**

##Memuat Dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/MyDrive/Check point AVD/consumer_electronics_sales_data.csv'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
df = pd.read_csv(path)
df

,ProductID,ProductCategory,ProductBrand,ProductPrice,CustomerAge,CustomerGender,PurchaseFrequency,CustomerSatisfaction,PurchaseIntent
0,5874,Smartphones,Other Brands,312.949668,18,0,2,1,0
1,5875,Smart Watches,Samsung,980.389404,35,1,7,2,1
2,5876,Tablets,Samsung,2606.718293,63,0,1,5,1
3,5877,Smartphones,Samsung,870.395450,63,1,10,3,1
4,5878,Tablets,Sony,1798.955875,57,0,17,3,0
...,...,...,...,...,...,...,...,...,...
8995,14869,Smart Watches,Samsung,1041.149163,36,1,16,4,0
8996,14870,Smartphones,Samsung,1485.694311,57,0,5,1,1
8997,14871,Headphones,Samsung,2887.369597,28,0,18,4,0
8998,14872,Tablets,HP,1490.453964,38,0,4,2,1
8999,14873,Smartphones,Sony,2315.583087,62,0,15,2,1

Alur kerja proyek ini dimulai dengan tahap Data Preparation untuk menjamin kualitas analisis melalui pembersihan nilai yang hilang dan melakukan encoding pada variabel kategori seperti gender dan kategori produk. Selanjutnya, dilakukan Exploratory Data Analysis (EDA) untuk memvisualisasikan distribusi demografi, tren penjualan periodik, serta komparasi performa antarproduk guna menangkap pola perilaku pasar yang signifikan. Pada tahap Modeling, algoritma Machine Learning seperti Random Forest atau Linear Regression diterapkan dan hasilnya akan diuji melalui tahap Evaluation menggunakan metrik MSE atau R2 Score untuk memastikan akurasi prediksi. Seluruh rangkaian ini diakhiri dengan tahap Deployment/Reporting, di mana temuan teknis dikonversi menjadi insight strategis yang siap dipresentasikan kepada tim manajemen untuk pengambilan keputusan bisnis yang tepat.

##**Deskripsi Data**

### **Struktur Data ( Informasi Lanjutan )**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ProductID             9000 non-null   int64
 1   ProductCategory       9000 non-null   object
 2   ProductBrand          9000 non-null   object
 3   ProductPrice          9000 non-null   float64
 4   CustomerAge           9000 non-null   int64
 5   CustomerGender        9000 non-null   int64
 6   PurchaseFrequency     9000 non-null   int64
 7   CustomerSatisfaction  9000 non-null   int64
 8   PurchaseIntent        9000 non-null   int64
dtypes: float64(1), int64(6), object(2)
memory usage: 632.9+ KB

1. ProductID: Jumlah baris: 9000 Tipe data: int64 Deskripsi: ID Unik Produk
2. ProductCategory: Jumlah baris: 9000 Tipe data: object Deskripsi: Kategori Produk
3. ProductBrand: Jumlah baris: 9000 Tipe data: object Deskripsi: Merek Produk
4. ProductPrice: Jumlah baris: 9000 Tipe data: float64 Deskripsi: Harga Produk
5. CustomerAge: Jumlah baris: 9000 Tipe data: int64 Deskripsi: Usia Pelanggan
6. CustomerGender: Jumlah baris: 9000 Tipe data: int64 Deskripsi: Jenis Kelamin Pelanggan
7. PurchaseFrequency: Jumlah baris: 9000 Tipe data: int64 Deskripsi: Frekuensi Pembelian
8. CustomerSatisfaction: Jumlah baris: 9000 Tipe data: int64 Deskripsi: Tingkat Kepuasan Pelanggan
9. PurchaseIntent: Jumlah baris: 9000 Tipe data: int64 Deskripsi: Niat Membeli Pelanggan (Target)

### **Informasi Statistik Deskriptif**

In [ ]:
df.describe(include='all')

,ProductID,ProductCategory,ProductBrand,ProductPrice,CustomerAge,CustomerGender,PurchaseFrequency,CustomerSatisfaction,PurchaseIntent
count,9000.000000,9000,9000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000
unique,NaN,5,5,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Laptops,Samsung,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1842,1854,NaN,NaN,NaN,NaN,NaN,NaN
mean,10373.500000,NaN,NaN,1527.429195,43.347000,0.508889,10.054667,2.996000,0.566444
std,2598.220545,NaN,NaN,829.900898,15.055084,0.499949,5.461328,1.405301,0.495593
min,5874.000000,NaN,NaN,100.376358,18.000000,0.000000,1.000000,1.000000,0.000000
25%,8123.750000,NaN,NaN,809.165014,30.000000,0.000000,5.000000,2.000000,0.000000
50%,10373.500000,NaN,NaN,1513.024577,43.000000,1.000000,10.000000,3.000000,1.000000
75%,12623.250000,NaN,NaN,2244.415520,56.000000,1.000000,15.000000,4.000000,1.000000
max,14873.000000,NaN,NaN,2999.852253,69.000000,1.000000,19.000000,5.000000,1.000000

1. Count (Kelengkapan Data)
Berdasarkan data, total baris transaksi adalah 9.000. Maka dapat disimpulkan:

Tidak ada data yang hilang pada setiap kolom (seluruh kolom berisi 9.000 data lengkap).

Kesimpulan: Seluruh kolom tidak mengandung missing values, sehingga dataset sudah lengkap dan siap digunakan untuk analisis lebih lanjut.

---

2. Mean vs Median (Distribusi Data)
Kolom ProductPrice

Mean = 1527,43

Median (50%) = 1513,02

Nilai rata-rata sangat mendekati median, menunjukkan distribusi harga produk yang relatif simetris.

Kolom CustomerAge

Mean = 43,35

Median (50%) = 43,00

Rata-rata yang hampir sama dengan median menandakan distribusi usia pelanggan cukup merata tanpa perbedaan ekstrem.

Kolom PurchaseFrequency

Mean = 10,05

Median (50%) = 10,00

Perbedaan yang sangat tipis menunjukkan distribusi frekuensi pembelian yang stabil dan seimbang.

Kesimpulan: Secara keseluruhan, data numerik pada dataset ini cenderung berdistribusi normal/simetris dan tidak menunjukkan skewness yang signifikan.

3. Min dan Max (Validasi Logika)
ProductPrice

Min = 100,38

Max = 2999,85

CustomerAge

Min = 18

Max = 69

CustomerSatisfaction

Min = 1

Max = 5

Kesimpulan:

Rentang ProductPrice (100 hingga 2.999) menunjukkan variasi harga yang luas, mencakup produk ekonomis hingga premium.

Rentang Usia (18–69 tahun) sangat logis untuk target konsumen dewasa.

Nilai Kepuasan berada dalam skala normal 1–5, sehingga tidak ada indikasi kesalahan input data.

4. Standar Deviasi (std) - Variabilitas Data
ProductPrice

Mean = 1527,43

Std = 829,90

PurchaseFrequency

Mean = 10,05

Std = 5,46

Kesimpulan:

Pada kolom ProductPrice, nilai standar deviasi yang besar menunjukkan variasi harga produk yang cukup lebar di dalam katalog.

Pada kolom PurchaseFrequency, standar deviasi sebesar 5,46 mengindikasikan adanya perbedaan yang cukup kontras antara pelanggan jarang (skala rendah) dan pelanggan setia (skala tinggi).

# **Data Preparation**

## **Mengecek Tipe Data**

In [ ]:
df.dtypes

ProductID                 int64
ProductCategory          object
ProductBrand             object
ProductPrice            float64
CustomerAge               int64
CustomerGender            int64
PurchaseFrequency         int64
CustomerSatisfaction      int64
PurchaseIntent            int64
dtype: object

Menurut saya, kode disini sudah benar dan cocok. Jadi tidak ada yang perlu diganti.

## **Mengidentifikasi Inconsistent Values**

In [ ]:
print(df['ProductCategory'].unique())

['Smartphones' 'Smart Watches' 'Tablets' 'Laptops' 'Headphones']

In [ ]:
print(df['ProductBrand'].unique())

['Other Brands' 'Samsung' 'Sony' 'HP' 'Apple']

In [ ]:
print(df['ProductPrice'].unique())

[ 312.94966811  980.38940432 2606.71829284 ... 2887.36959713 1490.45396391
 2315.58308746]

In [ ]:
df['ProductPrice'] = df['ProductPrice'].round().astype(int)

In [ ]:
print(df['ProductPrice'].unique())

[ 313  980 2607 ... 1775 1520 1490]

In [ ]:
print(df['CustomerAge'].unique())

[18 35 63 57 37 26 19 66 20 38 48 62 54 33 29 28 43 58 34 65 67 23 61 64
 55 56 42 39 50 52 40 41 30 47 60 21 49 27 51 25 69 44 24 22 53 68 46 45
 31 32 36 59]

In [ ]:
print(df['CustomerGender'].unique())

[0 1]

In [ ]:
print(df['PurchaseFrequency'].unique())

[ 2  7  1 10 17  8  5 12  3 14 16  4 18 15  9 19  6 11 13]

In [ ]:
print(df['CustomerSatisfaction'].unique())

[1 2 5 3 4]

In [ ]:
print(df['PurchaseIntent'].unique())

[0 1]

Dari hasil analisis saya:

 1. ProductCategory |
Pada data ini, sudah bersih dari Inconsistent Values, karena tidak ada pengulangan kata, maupun nomor anomali yang muncul.

2. ProductBrand |
Pada data ini, sudah bersih dari Inconsistent Values, karena tidak ada pengulangan kata dengan tulisan yang berbeda, tidak ada nomor anomali yang muncul, dan tidak ada kata selain nama brand.

3. ProductPrice |
Sebenarnya di data ini bisa dibilang tidak ada Inconsistent Values, namun ini sangat tidak wajar jika diperuntukkan sebagai Harga Produk. Maka saya ubah ke integer karena tipe ata ini, relevan untuk pecahan rupiah. ( Data Construction )

4. CustomerAge |
Pada data ini, sudah bersih dari Inconsistent Values, karena semua angka yang keluar masih masuk akal dengan umur manusia, dan tidak ada terselip data yang anomali.

5. CustomerGender |
Pada data ini sebenarnya sudah bersih dari Inconsistent Values, cuma kurag menjelaskan gender dari para pembeli.

6. CustomerFrequency |
Ini sudah konsisten karena yang keluar integer dan biasanya frekuensi pembelian biasanya dihitung dalam jumlah bilangan cacah.

7. CustomerSatisfaction |
Ini sudah konsisten, karena yang keluar full integer dan tidak ada data anomali yang keluar.

8. PurchaseIntent |
Ini juga konsisten yang keluar hanya angka dan tidak ada data anomali

## **Mengidentifikasi Missing Values.**

In [ ]:
pd.DataFrame(df.isna().sum() / len(df) * 100, columns=['Null Ratio in %'])

                      Null Ratio in %
ProductID                         0.0
ProductCategory                   0.0
ProductBrand                      0.0
ProductPrice                      0.0
CustomerAge                       0.0
CustomerGender                    0.0
PurchaseFrequency                 0.0
CustomerSatisfaction              0.0
PurchaseIntent                    0.0

Berdasarkan hasil data menunjukkan angka 0.0. Ini berarti setiap baris dalam dataset kamu telah terisi lengkap, dan tidak ada satu pun data yang kosong atau bernilai null di semua variabel tersebut.

## **Mengidentifikasi Duplicated Values.**

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [ProductID, ProductCategory, ProductBrand, ProductPrice, CustomerAge, CustomerGender, PurchaseFrequency, CustomerSatisfaction, PurchaseIntent]
Index: []

Aman dari Duplicated Values karena tidak ada data ganda.

Jika ada, kita bisa menggunakan kode df = df.drop_duplicates() untuk memperbaiki data dari Duplicated Values.

## **Mengidentifikasi Outliers**

# **Menyimpan Dataset**

In [ ]:
df.to_csv('Checkpoint 3 Andhika Fhariel', index=False)